name: "Pi 5 Fan Controller"
version: "0.9"
slug: "pi5fancontroller"
description: "This enables the fan on the Raspberry Pi 5 when running Home Assistant OS. You can control fan speeds, requires restart. Check logs for information."
arch:
  - aarch64
startup: "once"
auth_api: true
init: false
ingress: true
app_armor: false
privileged:
  - SYS_ADMIN
stage: "stable"
full_access: true
boot: "manual"
options:
  mode: "tyst"
  custom_temp0: 60
  custom_speed0: 75
  custom_temp1: 65
  custom_speed1: 150
schema:
  mode: list(tyst|balanserad|aggressiv|avstängd|custom)
  custom_temp0: int
  custom_speed0: int
  custom_temp1: int
  custom_speed1: int
